name: sip_script_runner
version: 0.0.3
description: The core package for sip, used to parse and run project commands/scripts
homepage: https://github.com/mrgnhnt96/sip
repository: https://github.com/mrgnhnt96/sip/tree/main/packages/script_runner
issue_tracker: https://github.com/mrgnhnt96/sip/issues
documentation: https://github.com/mrgnhnt96/sip/tree/master/packages/sip#readme
topics: [cli, executable, sip]
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  autoequal: ^0.9.0
  equatable: ^2.0.5
  ffi: ^2.1.0
  json_annotation: ^4.8.1
  mocktail: ^1.0.3
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  autoequal_gen: ^0.9.0
  build_runner: ^2.4.8
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  test: ^1.25.1
