name: sip_console
version: 0.0.6
description: A logger tool to interact with the console, used by the SIP CLI (package:sip_cli).
homepage: https://github.com/mrgnhnt96/sip
repository: https://github.com/mrgnhnt96/sip/tree/main/packages/console
issue_tracker: https://github.com/mrgnhnt96/sip/issues
documentation: https://github.com/mrgnhnt96/sip/tree/master/packages/sip#readme
topics: [cli, logger, sip]
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console2: ">=3.0.0 <4.0.0"
  get_it: ">=7.0.0 <8.0.0"
  io: ">=1.0.0 <2.0.0"
