name: sip_console
version: 0.0.1
description: A logger tool to interact with the console, used by the SIP CLI (package:sip).
homepage: https://github.com/mrgnhnt96/sip
repository: https://github.com/mrgnhnt96/sip
issue_tracker: https://github.com/mrgnhnt96/sip/issues
documentation: https://github.com/mrgnhnt96/sip/tree/master/packages/sip#readme
topics: [cli, logger, sip]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console2: ^3.0.0
  get_it: ^7.6.7
  io: ^1.0.4
