name: sip_console
version: 0.0.1
description: >
  A Tool to interact with the console for sip

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_console2: ^3.0.0
  get_it: ^7.6.7
  io: ^1.0.4
