on: workflow_dispatch

name: Compile blobs

env:
  BLOBS_DIR: lib/src/blobs

jobs:
  compile_blobs:
    strategy:
      matrix:
        # satifies linux (x64), macos (x64) and windows (x64)
        # to compile macos (arm64), use local machine
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo Version
        run: cargo --version

      - name: Compile Blob
        shell: bash
        id: blob
        run: bash packages/script_runner/scripts/compile_blob.sh x64

      - name: Set Windows Path
        id: set_windows_path
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          echo "Blob path (before update): ${{ steps.blob.outputs.BLOB_PATH }}"

          UPDATED_PATH=$(echo "${{ steps.blob.outputs.BLOB_PATH }}" | tr '/' '\\')
          echo "BLOB_PATH=$UPDATED_PATH" >>$GITHUB_OUTPUT

          echo "Blob path (updated): $UPDATED_PATH"
          echo "Blob path (outputs): ${{ steps.blob.outputs.BLOB_PATH }}"

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.blob.outputs.BLOB_FILE }}
          path: ${{ steps.blob.outputs.BLOB_PATH }}
          if-no-files-found: error

  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs:
      - compile_blobs
    if: ${{ needs.compile_blobs.result == 'success' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ${{ env.BLOBS_DIR }}

      - run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: blobs
          title: Blobs
          commit-message: "[CI] feat(BLOBS): compile blobs for all platforms"
