on: workflow_dispatch

name: Compile blobs

env:
  BLOBS_DIR: lib/src/blobs

jobs:
  compile_blobs:
    strategy:
      matrix:
        # satifies linux (x64), macos (x64) and windows (x64)
        # to compile macos (arm64), use local machine
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo Version
        run: cargo --version

      - name: Compile Blob
        shell: bash
        id: blob
        run: |
          SCRIPT_PATH="packages/script_runner/scripts/compile_blob.sh"

          if [[ ${{ matrix.os }} == 'windows-latest' ]]; then
              echo "gunna try this?"
              bash $SCRIPT_PATH x64

              SCRIPT_PATH=$(echo "$SCRIPT_PATH" | tr '/' '\\')
          fi

          bash $SCRIPT_PATH x64

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: ${{ steps.blob.outputs.BLOB_FILE }}
          path: packages\script_runnner\lib\src\blobs\windows_x64.dll
          if-no-files-found: error

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          name: ${{ steps.blob.outputs.BLOB_FILE }}
          path: ${{ steps.blob.outputs.BLOB_PATH }}
          if-no-files-found: error

  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs:
      - compile_blobs
    if: ${{ needs.compile_blobs.result == 'success' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ${{ env.BLOBS_DIR }}

      - run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: blobs
          title: Blobs
          commit-message: "[CI] feat(BLOBS): compile blobs for all platforms"
