on: workflow_dispatch

name: Compile blobs

env:
  BLOBS_DIR: lib/src/blobs

jobs:
  compile_blobs:
    strategy:
      matrix:
        # satifies linux (x64), macos (x64) and windows (x64)
        # to compile macos (arm64), use local machine
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup dart environment
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: cd packages/sip && dart pub get

      - name: Install sip
        run: cd packages/sip && dart pub global activate -s path . --overwrite

      - name: Add .pub_cache bin to path
        shell: bash
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Run sip version
        run: sip --version

      - name: Install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Compile Blob
        shell: bash
        id: blob
        run: |
          BLOB=${{ env.BLOBS_DIR }}/$FILE

          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
              OS="linux"
          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
              OS="macos"
          elif [[ ${{ matrix.os }} == 'windows-latest' ]]; then
              OS="windows"
              # UPDATE PATH TO USE PROPER PATH SEPARATOR
              BLOB=$(echo "$BLOB" | tr '/' '\\')
          fi

          echo "CWD: $(pwd)"

          sip run compile-blob -- --platform "$OS" --arch x64

          # add the BLOB path to the output
          echo "BLOB=$BLOB" >>"$GITHUB_OUTPUT"

          # Add the filename of the BLOB to the output
          echo "FILE=$FILE" >>"$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.blob.outputs.FILENAME }}
          path: ${{ steps.blob.outputs.BLOB }}

  create_pull_request:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs:
      - compile_blobs
    if: ${{ needs.compile_blobs.result == 'success' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ${{ env.BLOBS_DIR }}

      - run: git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: blobs
          title: Blobs
          commit-message: "[CI] feat(BLOBS): compile blobs for all platforms"
